name: 'My Awesome list'
description: 'Generate awesome list from user starred repositories'
branding:
  icon: align-justify
  color: yellow
inputs:
  github-token:
    description: 'Github token'
    required: true
  api-token:
    description: 'Personal API Token'
    required: true
  github-name:
    description: 'Name shown in the commit'
    default: 'GitHub Actions'
    required: false
  github-email:
    description: 'Email shown in the commit'
    default: 'actions@users.noreply.github.com'
    required: false
  template-path:
    required: false
    description: 'EJS template path relative to project root directory'
    default: 'TEMPLATE.ejs'
  output-filename:
    description: 'The output file name, default to README.md'
    required: false
    default: 'README.md'
runs:
  using: 'node12'
  main: 'index.js'
