name: 'Starlist'
description: 'Generate a list of user starred repositories'
inputs:
  api-token:
    description: 'Personal API Token'
    required: true
  compact-by-topic:
    description: 'Generate another page with output compacted by github topics'
    default: 'false'
    required: false
  github-name:
    description: 'Name shown in the commit'
    default: 'GitHub Actions'
    required: false
  github-email:
    description: 'Email shown in the commit'
    default: 'actions@users.noreply.github.com'
    required: false
  template-path:
    required: false
    description: 'EJS template path relative to project root directory'
    default: 'TEMPLATE.ejs'
  output-filename:
    description: 'The output file name, default to README.md'
    required: false
    default: 'README.md'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: align-justify
  color: yellow
