query GetUserStarredRepos($login: String!, $cursor: String) {
  viewer: user(login: $login) {
    login

    starredRepositories(first: 40, after: $cursor) {
      isOverLimit
      totalCount

      pageInfo {
        endCursor
        hasNextPage
      }

      edges {
        starredAt

        node {
          archivedAt
          description
          forkCount
          homepageUrl
          url
          isFork
          isPrivate
          isTemplate

          languages(first: 5, orderBy: { direction: DESC, field: SIZE }) {
            totalCount
            totalSize
            edges {
              node {
                name
              }
              size
            }
          }

          latestRelease {
            name
            publishedAt
          }

          licenseInfo {
            nickname
            spdxId
          }

          nameWithOwner
          parent {
            nameWithOwner
          }
          pushedAt

          repositoryTopics(first: 20) {
            totalCount
            nodes {
              topic {
                name
              }
              url
            }
          }

          stargazerCount
        }
      }
    }
  }
}
