query GetUserStarredRepos($login: String!, $cursor: String, $order: OrderDirection!) {
  user(login: $login) {
    login

    starredRepositories(first: 40, after: $cursor, orderBy: { field: STARRED_AT, direction: $order }) {
      isOverLimit
      totalCount

      pageInfo {
        endCursor
        hasNextPage
      }

      edges {
        starredAt

        node {
          archivedAt
          description
          forkCount
          homepageUrl
          url
          isFork
          isPrivate
          isTemplate

          languages(first: 10, orderBy: { direction: DESC, field: SIZE }) {
            totalCount
            totalSize
            edges {
              node {
                name
              }
              size
            }
          }

          latestRelease {
            name
            publishedAt
          }

          licenseInfo {
            spdxId
            name
            nickname
          }

          nameWithOwner
          parent {
            nameWithOwner
          }
          pushedAt

          repositoryTopics(first: 20) {
            totalCount
            nodes {
              topic {
                name
              }
              url
            }
          }

          stargazerCount
        }
      }
    }
  }
}
